use mago_allocator::LocalArena;
use mago_database::file::FileId;
use mago_syntax::cst::*;
use tower_lsp::lsp_types::{Location, Url};

use crate::Backend;
use crate::text_position::offset_to_position;

use super::helpers::{extract_string_literal, singularize_english_word};

/// Conventional route name suffixes generated by `Route::resource()`.
const RESOURCE_SUFFIXES: &[&str] = &[
    "index", "create", "store", "show", "edit", "update", "destroy",
];

/// Conventional route name suffixes generated by `Route::apiResource()`.
const API_RESOURCE_SUFFIXES: &[&str] = &["index", "store", "show", "update", "destroy"];

/// Split a resource name on `/` into the URI prefix it implies and the
/// resource itself.
///
/// Laravel's `ResourceRegistrar` treats a slash in the name as a request to
/// wrap the resource in a prefixed group, so `Route::resource('photos/comments')`
/// registers the resource `comments` under the URI prefix `photos` — the names
/// it generates are `comments.index`, not `photos.comments.index`.
fn split_resource_prefix(name: &str) -> (&str, &str) {
    let name = name.trim_matches('/');
    match name.rsplit_once('/') {
        Some((prefix, resource)) => (prefix, resource),
        None => ("", name),
    }
}

/// Build the filtered list of resource route suffixes, respecting
/// `->only()` and `->except()` modifiers.
fn filtered_resource_suffixes(
    is_api: bool,
    only: &[String],
    except: &[String],
) -> Vec<&'static str> {
    let base = if is_api {
        API_RESOURCE_SUFFIXES
    } else {
        RESOURCE_SUFFIXES
    };
    base.iter()
        .copied()
        .filter(|s| {
            if !only.is_empty() {
                only.iter().any(|o| o == s)
            } else if !except.is_empty() {
                !except.iter().any(|e| e == s)
            } else {
                true
            }
        })
        .collect()
}

/// Extract string values from `->only()`/`->except()` arguments.
///
/// Handles both array form `->only(['index', 'show'])` and individual
/// args `->except('create', 'edit')`.
fn extract_string_list_from_args<'a>(args: &'a ArgumentList<'a>, content: &'a str) -> Vec<String> {
    let mut values = Vec::new();
    for arg in args.arguments.iter() {
        match arg.value() {
            // Array form: ['index', 'show']
            Expression::Array(arr) => {
                for el in arr.elements.iter() {
                    if let ArrayElement::Value(v) = el
                        && let Some((val, _, _)) = extract_string_literal(v.value, content)
                    {
                        values.push(val.to_string());
                    }
                }
            }
            Expression::LegacyArray(arr) => {
                for el in arr.elements.iter() {
                    if let ArrayElement::Value(v) = el
                        && let Some((val, _, _)) = extract_string_literal(v.value, content)
                    {
                        values.push(val.to_string());
                    }
                }
            }
            // Individual string arg: 'create'
            other => {
                if let Some((val, _, _)) = extract_string_literal(other, content) {
                    values.push(val.to_string());
                }
            }
        }
    }
    values
}

/// Extract the key/value string pairs of an array argument, as
/// `->parameters(['photos' => 'grid'])` passes.
fn extract_string_pairs_from_args(args: &ArgumentList<'_>, content: &str) -> Vec<(String, String)> {
    let mut pairs = Vec::new();
    for arg in args.arguments.iter() {
        let elements = match arg.value() {
            Expression::Array(arr) => arr.elements.as_slice(),
            Expression::LegacyArray(arr) => arr.elements.as_slice(),
            _ => continue,
        };
        for el in elements {
            if let ArrayElement::KeyValue(kv) = el
                && let Some((key, _, _)) = extract_string_literal(kv.key, content)
                && let Some((value, _, _)) = extract_string_literal(kv.value, content)
            {
                pairs.push((key.to_string(), value.to_string()));
            }
        }
    }
    pairs
}

/// A `Route::resource()` / `Route::apiResource()` registration, together with
/// the chain modifiers that shape the routes it generates.
struct ResourceRegistration<'a> {
    /// The resource name exactly as written (`photos`, `photos.comments`).
    name: &'a str,
    /// Byte offset of the resource-name string literal, for go-to-definition.
    name_offset: usize,
    /// `true` for `apiResource()`, which omits the `create` and `edit` routes.
    is_api: bool,
    /// Route suffixes kept by `->only([…])`; empty when not restricted.
    only: Vec<String>,
    /// Route suffixes dropped by `->except([…])`; empty when not restricted.
    except: Vec<String>,
    /// `->parameters(['photos' => 'grid'])` wildcard-name overrides, keyed by
    /// the resource-name segment they replace.
    parameters: Vec<(String, String)>,
    /// `->shallow()`: the routes that identify a child by its own id drop the
    /// parent segments of a nested resource.
    shallow: bool,
    /// URI prefix the chain applies ahead of the registration, as
    /// `Route::prefix('admin')->resource(…)` does.
    uri_prefix: String,
}

/// Recognise a `resource()` / `apiResource()` call from its method selector
/// and arguments, whichever side of the chain it sits on.
///
/// This runs for every link of every call chain in a route file, so the method
/// name is compared in place rather than lowercased into a fresh allocation.
fn resource_call_info<'a>(
    method: &ClassLikeMemberSelector<'a>,
    args: &'a ArgumentList<'a>,
    content: &'a str,
) -> Option<(&'a str, usize, bool)> {
    let ClassLikeMemberSelector::Identifier(ident) = method else {
        return None;
    };
    let is_api = if ident.value.eq_ignore_ascii_case(b"resource") {
        false
    } else if ident.value.eq_ignore_ascii_case(b"apiResource") {
        true
    } else {
        return None;
    };
    let (res_name, start, _) =
        extract_string_literal(args.arguments.iter().next()?.value(), content)?;
    Some((res_name, start, is_api))
}

/// Recover the resource registration a call chain expresses, if any.
///
/// The registration call may be the static entry point
/// (`Route::resource('photos', …)`) or a link further along the chain
/// (`Route::prefix('admin')->resource('photos', …)`), and the modifiers that
/// follow it (`->only()`, `->parameters()`, `->shallow()`) are collected on
/// the way back out.  Returns `None` for any chain that registers no resource.
fn resource_registration<'a>(
    expr: &'a Expression<'a>,
    content: &'a str,
) -> Option<ResourceRegistration<'a>> {
    let new_registration = |(name, name_offset, is_api), uri_prefix| ResourceRegistration {
        name,
        name_offset,
        is_api,
        only: Vec::new(),
        except: Vec::new(),
        parameters: Vec::new(),
        shallow: false,
        uri_prefix,
    };

    match expr {
        Expression::Call(Call::StaticMethod(sc)) => {
            resource_call_info(&sc.method, &sc.argument_list, content)
                .map(|info| new_registration(info, String::new()))
        }
        Expression::Call(Call::Method(mc)) => {
            if let Some(info) = resource_call_info(&mc.method, &mc.argument_list, content) {
                // Anything ahead of the registration in the chain can only
                // contribute a URI prefix, so stop descending and read it.
                return Some(new_registration(info, chain_uri_prefix(mc.object, content)));
            }
            let mut registration = resource_registration(mc.object, content)?;
            let ClassLikeMemberSelector::Identifier(ident) = &mc.method else {
                return Some(registration);
            };
            let method = ident.value;
            if method.eq_ignore_ascii_case(b"only") {
                registration.only = extract_string_list_from_args(&mc.argument_list, content);
            } else if method.eq_ignore_ascii_case(b"except") {
                registration.except = extract_string_list_from_args(&mc.argument_list, content);
            } else if method.eq_ignore_ascii_case(b"parameters") {
                registration.parameters =
                    extract_string_pairs_from_args(&mc.argument_list, content);
            } else if method.eq_ignore_ascii_case(b"parameter") {
                // `->parameter('photos', 'grid')` overrides a single wildcard.
                let mut args = mc.argument_list.arguments.iter();
                if let Some((key, _, _)) = args
                    .next()
                    .and_then(|a| extract_string_literal(a.value(), content))
                    && let Some((value, _, _)) = args
                        .next()
                        .and_then(|a| extract_string_literal(a.value(), content))
                {
                    registration
                        .parameters
                        .push((key.to_string(), value.to_string()));
                }
            } else if method.eq_ignore_ascii_case(b"shallow") {
                registration.shallow = true;
            }
            Some(registration)
        }
        _ => None,
    }
}

/// The wildcard Laravel derives for one segment of a resource name.
///
/// `photos` yields `{photo}`; `->parameters(['photos' => 'grid'])` replaces the
/// derived name, and hyphens become underscores so the result is a legal
/// parameter name.
fn resource_wildcard(segment: &str, overrides: &[(String, String)]) -> String {
    let name = overrides
        .iter()
        .find(|(key, _)| key == segment)
        .map(|(_, value)| value.clone())
        .unwrap_or_else(|| singularize_english_word(segment));
    if name.as_bytes().contains(&b'-') {
        name.replace('-', "_")
    } else {
        name
    }
}

/// The URI a resource name maps to, before any per-route suffix.
///
/// Every segment but the last contributes its own wildcard, so
/// `photos.comments` becomes `photos/{photo}/comments` — the last segment's
/// wildcard belongs to the individual routes that identify a single record.
fn nested_resource_uri(segments: &[&str], overrides: &[(String, String)]) -> String {
    let mut uri = String::new();
    for (i, segment) in segments.iter().enumerate() {
        if i > 0 {
            uri.push('/');
        }
        uri.push_str(segment);
        if i + 1 < segments.len() {
            uri.push_str("/{");
            uri.push_str(&resource_wildcard(segment, overrides));
            uri.push('}');
        }
    }
    uri
}

/// Resolve `route('name')` to the `->name('name')` declaration in `routes/`.
///
/// Supports both explicit full-name declarations:
///   `Route::get('/create', ...)->name('admin.email.template.create')`
///
/// And group prefix notation:
///   `Route::name('admin.email.template.')->group(fn() { Route::get(...)->name('create'); })`
pub(crate) fn resolve_route_definitions(backend: &Backend, name: &str) -> Vec<Location> {
    let mut results = Vec::new();
    let mut scanned: std::collections::HashSet<std::path::PathBuf> =
        std::collections::HashSet::new();
    let snapshot = backend.user_file_symbol_maps();

    for (file_uri, _) in snapshot {
        if !file_uri.contains("/routes/") {
            continue;
        }
        let Ok(uri) = Url::parse(&file_uri) else {
            continue;
        };
        let Some(content) = backend.get_file_content(&file_uri) else {
            continue;
        };
        if let Ok(path) = uri.to_file_path() {
            scanned.insert(path.canonicalize().unwrap_or(path));
        }
        let file_dir = uri
            .to_file_path()
            .ok()
            .and_then(|p| p.parent().map(|d| d.to_path_buf()));
        results.extend(scan_route_file(&content, name, &uri, file_dir.as_deref()));
    }

    for route_path in &backend.laravel_provider_resources.read().route_files {
        let canonical = route_path
            .canonicalize()
            .unwrap_or_else(|_| route_path.clone());
        if !scanned.insert(canonical) {
            continue;
        }
        if let Ok(content) = std::fs::read_to_string(route_path)
            && let Ok(uri) = Url::from_file_path(route_path)
        {
            let file_dir = route_path.parent();
            results.extend(scan_route_file(&content, name, &uri, file_dir));
        }
    }

    results
}

// ─── Route file scanner ──────────────────────────────────────────────────────

fn scan_route_file(
    content: &str,
    target: &str,
    uri: &Url,
    file_dir: Option<&std::path::Path>,
) -> Vec<Location> {
    let arena = LocalArena::new();
    let file_id = FileId::new(b"input.php");
    let program = mago_syntax::parser::parse_file_content(&arena, file_id, content.as_bytes());
    let mut results = Vec::new();

    for stmt in program.statements.iter() {
        results.extend(scan_stmt(stmt, content, "", target, uri, file_dir));
    }
    results
}

fn scan_stmt<'a>(
    stmt: &Statement<'a>,
    content: &str,
    prefix: &str,
    target: &str,
    uri: &Url,
    file_dir: Option<&std::path::Path>,
) -> Vec<Location> {
    match stmt {
        Statement::Expression(e) => scan_expr(e.expression, content, prefix, target, uri, file_dir),
        Statement::Return(r) => r
            .value
            .map(|v| scan_expr(v, content, prefix, target, uri, file_dir))
            .unwrap_or_default(),
        _ => Vec::new(),
    }
}

/// Walk a call-chain expression while tracking the accumulated group name prefix.
///
/// Handles two forms of group calls:
/// - Fluent chain: `Route::name('prefix.')->middleware(…)->group(fn(){…})`
///   (outermost node is `Call::Method`)
/// - Direct static: `Route::group(['as'=>'prefix.', …], fn(){…})`
///   (outermost node is `Call::StaticMethod`)
fn scan_expr<'a>(
    expr: &Expression<'a>,
    content: &str,
    prefix: &str,
    target: &str,
    uri: &Url,
    file_dir: Option<&std::path::Path>,
) -> Vec<Location> {
    // A chain that registers a resource declares every one of its route names
    // at the resource-name literal, so that is where the target resolves to.
    if let Some(registration) = resource_registration(expr, content) {
        let mut routes = Vec::new();
        let group = GroupPrefix {
            name: prefix,
            uri: "",
        };
        push_resource_routes(&registration, group, &mut routes);
        if routes.iter().any(|route| route.name == target) {
            return vec![crate::definition::point_location(
                uri.clone(),
                offset_to_position(content, registration.name_offset),
            )];
        }
        return Vec::new();
    }

    match expr {
        // ── Fluent instance-method chain: ->group() / ->name() / other ──────
        Expression::Call(Call::Method(mc)) => {
            let mut results = Vec::new();
            let ClassLikeMemberSelector::Identifier(ident) = &mc.method else {
                return scan_expr(mc.object, content, prefix, target, uri, file_dir);
            };
            let method = ident.value.to_ascii_lowercase();

            if method == b"group" {
                let chain_prefix = chain_name_prefix(mc.object, content);
                let new_prefix = format!("{prefix}{chain_prefix}");
                for arg in mc.argument_list.arguments.iter() {
                    results.extend(scan_group_body(
                        arg.value(),
                        content,
                        &new_prefix,
                        target,
                        uri,
                        file_dir,
                    ));
                }
            } else if method == b"name" {
                if let Some(first_arg) = mc.argument_list.arguments.iter().next()
                    && let Some((name_val, start, _)) =
                        extract_string_literal(first_arg.value(), content)
                {
                    let full = format!("{prefix}{name_val}");
                    if full == target {
                        results.push(crate::definition::point_location(
                            uri.clone(),
                            offset_to_position(content, start),
                        ));
                    }
                }
                results.extend(scan_expr(mc.object, content, prefix, target, uri, file_dir));
            } else {
                results.extend(scan_expr(mc.object, content, prefix, target, uri, file_dir));
            }
            results
        }

        // ── Direct static call: Route::group ────────────────────────────────
        Expression::Call(Call::StaticMethod(sc)) => {
            let ClassLikeMemberSelector::Identifier(ident) = &sc.method else {
                return Vec::new();
            };
            let method_lower = ident.value.to_ascii_lowercase();

            if method_lower == b"group" {
                let mut results = Vec::new();
                let array_prefix = extract_as_prefix_from_args(
                    sc.argument_list.arguments.iter().map(|a| a.value()),
                    content,
                );
                let new_prefix = format!("{prefix}{array_prefix}");
                for arg in sc.argument_list.arguments.iter() {
                    results.extend(scan_group_body(
                        arg.value(),
                        content,
                        &new_prefix,
                        target,
                        uri,
                        file_dir,
                    ));
                }
                results
            } else {
                Vec::new()
            }
        }

        _ => Vec::new(),
    }
}

/// Walk the argument that was passed to `->group()`.
///
/// Handles closures, arrow functions, and `__DIR__ . '/sub.php'` file
/// includes so that go-to-definition works on route names defined in
/// included sub-files.
fn scan_group_body<'a>(
    expr: &Expression<'a>,
    content: &str,
    prefix: &str,
    target: &str,
    uri: &Url,
    file_dir: Option<&std::path::Path>,
) -> Vec<Location> {
    match expr {
        Expression::Closure(closure) => {
            let mut results = Vec::new();
            for stmt in closure.body.statements.iter() {
                results.extend(scan_stmt(stmt, content, prefix, target, uri, file_dir));
            }
            results
        }
        Expression::ArrowFunction(af) => {
            scan_expr(af.expression, content, prefix, target, uri, file_dir)
        }
        _ => {
            // Follow `Route::group([], __DIR__ . '/sub.php')` file includes.
            // Parse the included file and scan it with the current prefix
            // so routes inherit the parent group's name prefix.
            // (Do NOT call `scan_route_file` — it resets the prefix to "".)
            if let Some(dir) = file_dir
                && let Some(rel_path) = extract_dir_concat_path(expr, content)
            {
                let included = dir.join(rel_path.trim_start_matches('/'));
                if let Ok(ref included_content) = std::fs::read_to_string(&included) {
                    let sub_uri = Url::from_file_path(&included).unwrap_or_else(|_| uri.clone());
                    let sub_dir = included.parent().map(|d| d.to_path_buf());
                    let arena = LocalArena::new();
                    let fid = FileId::new(b"included.php");
                    let prog = mago_syntax::parser::parse_file_content(
                        &arena,
                        fid,
                        included_content.as_bytes(),
                    );
                    let mut results = Vec::new();
                    for stmt in prog.statements.iter() {
                        results.extend(scan_stmt(
                            stmt,
                            included_content,
                            prefix,
                            target,
                            &sub_uri,
                            sub_dir.as_deref(),
                        ));
                    }
                    return results;
                }
            }
            Vec::new()
        }
    }
}

/// A named route recovered from the project's route files.
#[derive(Debug)]
pub(crate) struct RouteEntry {
    /// Fully-qualified route name, with group name prefixes applied
    /// (e.g. `admin.users.index`).
    pub name: String,
    /// The URI the route was registered with, with group URI prefixes
    /// applied and reported the way Laravel's `Route::uri()` does: no
    /// leading slash, and `/` for the root route (e.g. `users/{user}`).
    ///
    /// Empty when the URI is not statically recoverable — a variable URI,
    /// or a name generated by `Route::resource()` rather than written out.
    pub uri: String,
}

/// The name and URI prefixes a route inherits from the groups enclosing it.
#[derive(Clone, Copy, Default)]
struct GroupPrefix<'a> {
    /// Accumulated route-name prefix (`->name('admin.')`, `['as' => …]`).
    name: &'a str,
    /// Accumulated URI prefix (`->prefix('admin')`, `['prefix' => …]`).
    uri: &'a str,
}

/// Registration methods whose first argument is the route URI.
const URI_FIRST_ARG_METHODS: &[&[u8]] = &[
    b"get",
    b"post",
    b"put",
    b"patch",
    b"delete",
    b"options",
    b"any",
    b"view",
    b"redirect",
    b"permanentredirect",
];

/// Recover the URI a route was registered with from its call chain.
///
/// The walk starts at the receiver of `->name()` and descends through the
/// chain links until it reaches the registration call, so modifiers between
/// the two are skipped:
/// `Route::middleware('auth')->get('/users/{user}', …)->name('users.show')`
/// records `/users/{user}`.  `Route::match(['get', 'post'], '/uri', …)` keeps
/// its URI in the second argument.
fn chain_uri<'c>(expr: &Expression<'_>, content: &'c str) -> Option<&'c str> {
    let (method, args) = match expr {
        Expression::Call(Call::Method(mc)) => match &mc.method {
            ClassLikeMemberSelector::Identifier(ident) => (ident.value, &mc.argument_list),
            _ => return chain_uri(mc.object, content),
        },
        Expression::Call(Call::StaticMethod(sc)) => match &sc.method {
            ClassLikeMemberSelector::Identifier(ident) => (ident.value, &sc.argument_list),
            _ => return None,
        },
        _ => return None,
    };

    let lower = method.to_ascii_lowercase();
    let uri_arg = if URI_FIRST_ARG_METHODS.contains(&lower.as_slice()) {
        args.arguments.iter().next()
    } else if lower == b"match" {
        args.arguments.iter().nth(1)
    } else {
        None
    };
    if let Some(arg) = uri_arg {
        return extract_string_literal(arg.value(), content).map(|(uri, _, _)| uri);
    }

    // Not a registration link — keep descending the chain.
    match expr {
        Expression::Call(Call::Method(mc)) => chain_uri(mc.object, content),
        _ => None,
    }
}

/// Build the recorded URI of a route from its group prefix and own URI.
fn route_uri(group_uri: &str, own_uri: Option<&str>) -> String {
    let Some(own_uri) = own_uri else {
        return String::new();
    };
    let joined = join_uri_segments(group_uri, own_uri);
    if joined.is_empty() {
        "/".to_string()
    } else {
        joined
    }
}

/// Extract the parameter names from a route URI pattern.
///
/// `users/{user}/posts/{post?}` yields `["user", "post"]`: the optional
/// marker and the scoped-binding field of `{post:slug}` are stripped, so the
/// result is exactly the keys `route()`'s parameters array accepts.
pub(crate) fn route_uri_parameters(uri: &str) -> Vec<&str> {
    let mut params = Vec::new();
    let mut rest = uri;
    while let Some(open) = rest.find('{') {
        rest = &rest[open + 1..];
        let Some(close) = rest.find('}') else {
            break;
        };
        let raw = &rest[..close];
        rest = &rest[close + 1..];
        let name = raw
            .split_once(':')
            .map_or(raw, |(name, _field)| name)
            .trim_end_matches('?');
        if !name.is_empty() {
            params.push(name);
        }
    }
    params
}

/// Collect all named routes defined in `routes/` files.
///
/// Returns a sorted, deduplicated list of fully-qualified route names with
/// the URI each was registered with.
///
/// Follows `Route::group([], __DIR__ . '/sub.php')` file includes so
/// that routes in sub-files inherit the parent group's prefixes.
pub(crate) fn enumerate_all_routes(backend: &Backend) -> Vec<RouteEntry> {
    let mut routes = Vec::new();
    let mut scanned: std::collections::HashSet<std::path::PathBuf> =
        std::collections::HashSet::new();
    let snapshot = backend.user_file_symbol_maps();

    for (file_uri, _) in snapshot {
        if !file_uri.contains("/routes/") {
            continue;
        }
        // Skip sub-directory route files at the top level — they are
        // included by parent files via `Route::group([], __DIR__ . '/sub.php')`
        // and should only be scanned in that context to inherit the
        // correct name prefix.  A "sub-directory" file is one where the
        // path after the last `/routes/` segment contains another `/`.
        if let Some(after) = file_uri.rsplit("/routes/").next()
            && after.contains('/')
        {
            continue;
        }
        let Some(content) = backend.get_file_content(&file_uri) else {
            continue;
        };
        let path = Url::parse(&file_uri)
            .ok()
            .and_then(|u| u.to_file_path().ok());
        if let Some(ref p) = path {
            scanned.insert(p.canonicalize().unwrap_or_else(|_| p.clone()));
        }
        let file_dir = path
            .as_ref()
            .and_then(|p| p.parent().map(|d| d.to_path_buf()));
        collect_all_names_from_file(&content, file_dir.as_deref(), &mut routes);
    }

    for route_path in &backend.laravel_provider_resources.read().route_files {
        let canonical = route_path
            .canonicalize()
            .unwrap_or_else(|_| route_path.clone());
        if !scanned.insert(canonical) {
            continue;
        }
        if let Ok(content) = std::fs::read_to_string(route_path) {
            let file_dir = route_path.parent();
            collect_all_names_from_file(&content, file_dir, &mut routes);
        }
    }

    // One entry per name, as the name enumeration has always been.  Sorting
    // known URIs ahead of unknown ones means a name registered both with a
    // literal URI and by `Route::resource()` keeps the URI it has.
    routes.sort_by(|a, b| {
        a.name
            .cmp(&b.name)
            .then_with(|| a.uri.is_empty().cmp(&b.uri.is_empty()))
            .then_with(|| a.uri.cmp(&b.uri))
    });
    routes.dedup_by(|a, b| a.name == b.name);
    routes
}

/// Parse a single route file and collect every `->name('...')` value,
/// accounting for group prefixes and file includes.
fn collect_all_names_from_file(
    content: &str,
    file_dir: Option<&std::path::Path>,
    out: &mut Vec<RouteEntry>,
) {
    let arena = LocalArena::new();
    let file_id = FileId::new(b"input.php");
    let program = mago_syntax::parser::parse_file_content(&arena, file_id, content.as_bytes());
    for stmt in program.statements.iter() {
        collect_names_from_stmt(stmt, content, GroupPrefix::default(), file_dir, out);
    }
}

fn collect_names_from_stmt<'a>(
    stmt: &Statement<'a>,
    content: &str,
    group: GroupPrefix<'_>,
    file_dir: Option<&std::path::Path>,
    out: &mut Vec<RouteEntry>,
) {
    match stmt {
        Statement::Expression(e) => {
            collect_names_from_expr(e.expression, content, group, file_dir, out);
        }
        Statement::Return(r) => {
            if let Some(v) = r.value {
                collect_names_from_expr(v, content, group, file_dir, out);
            }
        }
        _ => {}
    }
}

fn collect_names_from_expr<'a>(
    expr: &Expression<'a>,
    content: &str,
    group: GroupPrefix<'_>,
    file_dir: Option<&std::path::Path>,
    out: &mut Vec<RouteEntry>,
) {
    // A chain that registers a resource generates its whole route set here;
    // none of the per-route handling below applies to it.
    if let Some(registration) = resource_registration(expr, content) {
        push_resource_routes(&registration, group, out);
        return;
    }

    match expr {
        Expression::Call(Call::Method(mc)) => {
            let ClassLikeMemberSelector::Identifier(ident) = &mc.method else {
                collect_names_from_expr(mc.object, content, group, file_dir, out);
                return;
            };
            let method = ident.value.to_ascii_lowercase();

            if method == b"group" {
                let name_prefix =
                    format!("{}{}", group.name, chain_name_prefix(mc.object, content));
                let uri_prefix =
                    join_uri_segments(group.uri, &chain_uri_prefix(mc.object, content));
                let inner = GroupPrefix {
                    name: &name_prefix,
                    uri: &uri_prefix,
                };
                for arg in mc.argument_list.arguments.iter() {
                    collect_names_from_group_body(arg.value(), content, inner, file_dir, out);
                }
            } else if method == b"name" {
                if let Some(first_arg) = mc.argument_list.arguments.iter().next()
                    && let Some((name_val, _, _)) =
                        extract_string_literal(first_arg.value(), content)
                {
                    let full = format!("{}{name_val}", group.name);
                    // Only collect leaf names (non-prefix names that don't end with '.').
                    if !full.is_empty() && !full.ends_with('.') {
                        // A `->prefix()` on the route's own chain
                        // (`Route::prefix('admin')->get(…)`) prefixes the URI
                        // just as an enclosing group's does.
                        let uri_prefix =
                            join_uri_segments(group.uri, &chain_uri_prefix(mc.object, content));
                        out.push(RouteEntry {
                            name: full,
                            uri: route_uri(&uri_prefix, chain_uri(mc.object, content)),
                        });
                    }
                }
                collect_names_from_expr(mc.object, content, group, file_dir, out);
            } else {
                collect_names_from_expr(mc.object, content, group, file_dir, out);
            }
        }
        Expression::Call(Call::StaticMethod(sc)) => {
            let ClassLikeMemberSelector::Identifier(ident) = &sc.method else {
                return;
            };
            let method_lower = ident.value.to_ascii_lowercase();

            if method_lower == b"group" {
                let args = || sc.argument_list.arguments.iter().map(|a| a.value());
                let name_prefix = format!(
                    "{}{}",
                    group.name,
                    extract_as_prefix_from_args(args(), content)
                );
                let uri_prefix =
                    join_uri_segments(group.uri, &extract_uri_prefix_from_args(args(), content));
                let inner = GroupPrefix {
                    name: &name_prefix,
                    uri: &uri_prefix,
                };
                for arg in sc.argument_list.arguments.iter() {
                    collect_names_from_group_body(arg.value(), content, inner, file_dir, out);
                }
            }
        }
        _ => {}
    }
}

/// Record the conventional routes a `Route::resource()` registration
/// generates, deriving each URI from the resource name the way Laravel's
/// `ResourceRegistrar` does.
fn push_resource_routes(
    registration: &ResourceRegistration<'_>,
    group: GroupPrefix<'_>,
    out: &mut Vec<RouteEntry>,
) {
    let (path_prefix, resource) = split_resource_prefix(registration.name);
    let segments: Vec<&str> = resource.split('.').filter(|s| !s.is_empty()).collect();
    let Some(last) = segments.last().copied() else {
        return;
    };

    // Every URI prefix in scope — the enclosing groups', the chain's own, and
    // the one a slash in the resource name implies — is applied once here
    // rather than per generated route.
    let uri_prefix = join_uri_segments(
        &join_uri_segments(group.uri, &registration.uri_prefix),
        path_prefix,
    );
    let collection_name = segments.join(".");
    let collection_uri = join_uri_segments(
        &uri_prefix,
        &nested_resource_uri(&segments, &registration.parameters),
    );
    // `->shallow()` reduces a nested resource to its last segment on the
    // routes that already identify the child by its own id — the name loses
    // the parent segments along with the URI.
    let shallow_uri = registration
        .shallow
        .then(|| join_uri_segments(&uri_prefix, last));
    let (member_uri, member_name): (&str, &str) = match shallow_uri.as_deref() {
        Some(uri) => (uri, last),
        None => (&collection_uri, &collection_name),
    };
    let wildcard = resource_wildcard(last, &registration.parameters);

    let suffixes = filtered_resource_suffixes(
        registration.is_api,
        &registration.only,
        &registration.except,
    );
    for suffix in suffixes {
        let (name_base, uri) = match suffix {
            "create" => (collection_name.as_str(), format!("{collection_uri}/create")),
            "show" | "update" | "destroy" => (member_name, format!("{member_uri}/{{{wildcard}}}")),
            "edit" => (member_name, format!("{member_uri}/{{{wildcard}}}/edit")),
            // index and store.
            _ => (collection_name.as_str(), collection_uri.clone()),
        };
        out.push(RouteEntry {
            name: format!("{}{name_base}.{suffix}", group.name),
            uri,
        });
    }
}

fn collect_names_from_group_body<'a>(
    expr: &Expression<'a>,
    content: &str,
    group: GroupPrefix<'_>,
    file_dir: Option<&std::path::Path>,
    out: &mut Vec<RouteEntry>,
) {
    match expr {
        Expression::Closure(closure) => {
            for stmt in closure.body.statements.iter() {
                collect_names_from_stmt(stmt, content, group, file_dir, out);
            }
        }
        Expression::ArrowFunction(af) => {
            collect_names_from_expr(af.expression, content, group, file_dir, out);
        }
        _ => {
            // Handle `Route::group([], __DIR__ . '/sub.php')` file includes.
            // The expression is a binary concatenation: `__DIR__ . '/path'`.
            if let Some(dir) = file_dir
                && let Some(rel_path) = extract_dir_concat_path(expr, content)
            {
                let included = dir.join(rel_path.trim_start_matches('/'));
                if let Ok(included_content) = std::fs::read_to_string(&included) {
                    let sub_dir = included.parent().map(|d| d.to_path_buf());
                    // Scan the included file with the current prefix so
                    // routes inherit the parent group's name (e.g.
                    // "eaglesys::").  Do NOT scan with empty prefix —
                    // that produces unprefixed names that are incorrect.
                    let arena2 = LocalArena::new();
                    let fid2 = FileId::new(b"included.php");
                    let prog2 = mago_syntax::parser::parse_file_content(
                        &arena2,
                        fid2,
                        included_content.as_bytes(),
                    );
                    for stmt in prog2.statements.iter() {
                        collect_names_from_stmt(
                            stmt,
                            &included_content,
                            group,
                            sub_dir.as_deref(),
                            out,
                        );
                    }
                }
            }
        }
    }
}

use super::helpers::{
    chain_uri_prefix, extract_dir_concat_path, extract_uri_prefix_from_args, join_uri_segments,
};

pub(crate) use super::helpers::{chain_name_prefix, extract_as_prefix_from_args};

#[cfg(test)]
#[path = "route_names_tests.rs"]
mod tests;
